import { createInterface, Interface } from "node:readline/promises";
import { writeFile, access } from "node:fs/promises";
import { resolve } from "node:path";
import { CliOutput } from "../output";

const CONFIG_FILENAME = "atlas.config.yaml";

/**
 * Generates atlas.config.yaml via an interactive prompt sequence.
 *
 * In non-interactive environments (CI, piped stdin) the command fails early
 * with a clear message rather than producing a broken configuration.
 *
 * Secrets (Figma token, API keys) are NEVER collected — the generated config
 * uses ${ENV_VAR} placeholders and the user exports variables separately.
 */
export async function runInit(output: CliOutput): Promise<number> {
  if (!isInteractive()) {
    output.error(
      "atlas init requires an interactive terminal.\n" +
        "  In CI, create atlas.config.yaml manually or copy examples/basic/atlas.config.yaml.\n" +
        "  Then run: atlas doctor"
    );
    return 2;
  }

  const configPath = resolve(process.cwd(), CONFIG_FILENAME);
  const rl = createInterface({ input: process.stdin, output: process.stdout });

  try {
    if (await fileExists(configPath)) {
      const overwrite = await confirm(rl, `${CONFIG_FILENAME} already exists. Overwrite?`, false);
      if (!overwrite) {
        output.info("Initialization cancelled. Existing configuration is unchanged.");
        return 0;
      }
    }

    output.always("\nAtlas Visual Setup\n");

    const projectName = await ask(rl, "Project name", "My Website");
    const environment = await ask(rl, "Environment", "local");
    const targetUrl = await ask(rl, "Target URL", "https://example.com");
    const pageId = await ask(rl, "Page ID", "homepage");
    const figmaNodeId = await ask(rl, "Figma node ID (leave empty to use ${FIGMA_NODE_ID})", "");

    output.info("\nReports:");
    const htmlEnabled = await confirm(rl, "Enable HTML report?", true);
    const jsonEnabled = await confirm(rl, "Enable JSON report?", true);

    output.info("\nActions:");
    const qaseEnabled = await confirm(rl, "Enable Qase integration?", false);

    const yaml = buildConfigYaml({
      projectName,
      environment,
      targetUrl,
      pageId,
      figmaNodeId,
      htmlEnabled,
      jsonEnabled,
      qaseEnabled,
    });

    await writeFile(configPath, yaml, "utf8");

    output.blank();
    output.pass(`Created ${CONFIG_FILENAME}`);
    output.blank();
    output.info("Next steps:");
    output.info("  1. Set your Figma credentials:");
    output.info('     export FIGMA_TOKEN="your-figma-token"');
    output.info('     export FIGMA_FILE_KEY="your-file-key"');
    if (figmaNodeId) {
      output.info(`     (Figma node ID set to: ${figmaNodeId} — already in config)`);
    } else {
      output.info('     export FIGMA_NODE_ID="your-node-id"');
    }
    output.info("  2. Run: atlas doctor");
    output.info("  3. Run: atlas validate");

    return 0;
  } finally {
    rl.close();
  }
}

function buildConfigYaml(opts: {
  projectName: string;
  environment: string;
  targetUrl: string;
  pageId: string;
  figmaNodeId: string;
  htmlEnabled: boolean;
  jsonEnabled: boolean;
  qaseEnabled: boolean;
}): string {
  const nodeIdValue = opts.figmaNodeId || "${FIGMA_NODE_ID}";
  return `# Atlas Visual configuration — generated by atlas init

project:
  name: ${opts.projectName}

environment: ${opts.environment}

browser:
  provider: playwright
  headless: true
  timeout: 30000
  viewport:
    width: 1440
    height: 900

visual:
  enabled: true
  pages:
    - id: ${opts.pageId}
      url: ${opts.targetUrl}
      reference:
        provider: figma
        fileKey: \${FIGMA_FILE_KEY}
        nodeId: "${nodeIdValue}"
      comparison:
        pixelThreshold: 0.1
        allowedDifferencePercentage: 1.0

report:
  enabled: true
  outputDirectory: artifacts
  html:
    enabled: ${opts.htmlEnabled}
  json:
    enabled: ${opts.jsonEnabled}

actions:
  qase:
    enabled: ${opts.qaseEnabled}
    onlyOnFailure: true
    environments:
      - staging
      - production
  slack:
    enabled: false
`;
}

function isInteractive(): boolean {
  return Boolean(process.stdin.isTTY) && !process.env.CI;
}

async function ask(rl: Interface, prompt: string, defaultValue: string): Promise<string> {
  const hint = defaultValue ? ` (${defaultValue})` : "";
  const answer = await rl.question(`${prompt}${hint}: `);
  return answer.trim() || defaultValue;
}

async function confirm(rl: Interface, prompt: string, defaultValue: boolean): Promise<boolean> {
  const hint = defaultValue ? "[Y/n]" : "[y/N]";
  const answer = (await rl.question(`${prompt} ${hint}: `)).trim().toLowerCase();
  if (!answer) return defaultValue;
  return answer === "y" || answer === "yes";
}

async function fileExists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}
